title: "Fatma Amor - Data Analyst"
description: "Portfolio & Projects"
theme: jekyll-theme-slate

baseurl: ""
url: "https://fatmaamor.github.io"

nav:
  - name: "Home"
    link: /
  - name: "Projects"
    link: /projets
  - name: "Contact"
    link: /contact
