title: "Fatma Amor - Data Analyst"
description: "Portfolio & Projects"
theme: jekyll-theme-slate


nav:
  - name: "Home"
    link: /
  - name: "Projects"
    link: /projet/
  - name: "Contact"
    link: /contact/
