title: "Fatma Amor - Data Analyst"
description: "Portfolio & Projects"
theme: jekyll-theme-slate

baseurl: "/fatmaamor.github.io"

nav:
  - name: "Home"
    link: /
  - name: "Projects"
    link: /project
  - name: "Contact"
    link: /contact
